In [34]:
import requests
import pandas as pd

url = "https://stephen-king-api.onrender.com/api/books"

response = requests.get(url)
json_data = response.json()

print(type(json_data['data']))
print(len(json_data['data']))

<class 'list'>
64

In [35]:
df = pd.json_normalize(json_data['data'])

In [36]:
df.shape

(64, 10)

In [37]:
df

,id,Year,Title,handle,Publisher,ISBN,Pages,Notes,created_at,villains
0,1,1974,Carrie,carrie,Doubleday,978-0-385-08695-0,199,[],2023-11-13T23:48:47.848Z,"[{'name': 'Tina Blake', 'url': 'https://stephe..."
1,2,1975,Salem's Lot,salem-s-lot,Doubleday,978-0-385-00751-1,439,"[Nominee, World Fantasy Award, 1976[2]]",2023-11-13T23:48:48.098Z,"[{'name': 'Kurt Barlow', 'url': 'https://steph..."
2,3,1977,The Shining,the-shining,Doubleday,978-0-385-12167-5,447,"[Runner-up (4th place), Locus Award for Best F...",2023-11-13T23:48:48.219Z,"[{'name': 'Horace M. Derwent', 'url': 'https:/..."
3,4,1977,Rage,rage,Signet Books,978-0-451-07645-8,211,[Published under pseudonym Richard Bachman],2023-11-13T23:48:48.339Z,[]
4,5,1978,The Stand,the-stand,Doubleday,978-0-385-12168-2,823,"[Nominee, World Fantasy Award, 1979, Runner-up...",2023-11-13T23:48:48.477Z,"[{'name': 'Donald Merwin Elbert', 'url': 'http..."
...,...,...,...,...,...,...,...,...,...,...
59,60,2018,Elevation,elevation,Scribner,978-1-98210-231-9,144,[],2023-11-13T23:48:55.291Z,[]
60,61,2019,The Institute,the-institute,Scribner,978-1-98211-056-7,576,"[Nominee, British Fantasy Award's August Derle...",2023-11-13T23:48:55.457Z,"[{'name': 'Gladys Hickson', 'url': 'https://st..."
61,62,2021,Later,later,Hard Case Crime,978-1-78909-649-1,256,[],2023-11-13T23:48:55.579Z,[]
62,63,2021,Billy Summers,billy-summers,Scribner,978-1-982-17361-6,528,[],2023-11-13T23:48:55.753Z,[]
63,72,1979,The Roopak Zone,the-roopak-zone,Viking Press,978-0-670-26069697-5,428,"[Runner-up (2nd place), Locus Award for Best F...",2026-06-26T18:20:32.285Z,[]

In [41]:
df=df[['id', 'Title', 'ISBN','villains','Pages']]

In [42]:
df

,id,Title,ISBN,villains,Pages
0,1,Carrie,978-0-385-08695-0,"[{'name': 'Tina Blake', 'url': 'https://stephe...",199
1,2,Salem's Lot,978-0-385-00751-1,"[{'name': 'Kurt Barlow', 'url': 'https://steph...",439
2,3,The Shining,978-0-385-12167-5,"[{'name': 'Horace M. Derwent', 'url': 'https:/...",447
3,4,Rage,978-0-451-07645-8,[],211
4,5,The Stand,978-0-385-12168-2,"[{'name': 'Donald Merwin Elbert', 'url': 'http...",823
...,...,...,...,...,...
59,60,Elevation,978-1-98210-231-9,[],144
60,61,The Institute,978-1-98211-056-7,"[{'name': 'Gladys Hickson', 'url': 'https://st...",576
61,62,Later,978-1-78909-649-1,[],256
62,63,Billy Summers,978-1-982-17361-6,[],528
63,72,The Roopak Zone,978-0-670-26069697-5,[],428